import type { SchemaPatch } from "./patches.types";

// RustMaps API incorrectly defines this enum as an integer, but it's actually a string enum
export const monumentTypesSchemaPatch: SchemaPatch = (schema) => {
  if (schema.type === "string") return;
  schema.type = "string";
  console.log(schema);

  // HACK: These are unconfirmed. Based on comparing the enum names from the OpenAPI spec with the actual requests made by the Rust Maps website
  schema.enum = [
    "Outpost",
    "Bandit Town",
    "Fishing Village A",
    "Fishing Village B",
    "Fishing Village C",
    "Ranch",
    "Large Barn",
    "Excavator",
    "Airfield",
    "Junkyard",
    "Launch Site",
    "Military Tunnels",
    "Powerplant",
    "Radtown",
    "Trainyard",
    "Water Treatment",
    "Sphere Tank",
    "Satellite Dish",
    "Large Oilrig",
    "Small Oilrig",
    "Nuclear Missile Silo",
    "Ziggurat",
    "Gas Station",
    "Supermarket",
    "Warehouse",
    "Lighthouse",
    "Sewer Branch",
    "Swamp A",
    "Swamp B",
    "Swamp C",
    "Military Base A",
    "Military Base B",
    "Military Base C",
    "Military Base D",
    "Arctic Research Base A",
    "Small Harbor",
    "Large Harbor",
    "Ferry Terminal",
    "Water Well A",
    "Water Well B",
    "Water Well C",
    "Water Well D",
    "Water Well E",
    "Cave Large Hard",
    "Cave Large Medium",
    "Cave Large Sewers Hard",
    "Cave Medium Easy",
    "Cave Medium Hard",
    "Cave Medium Medium",
    "Cave Small Easy",
    "Cave Small Hard",
    "Cave Small Medium",
    "Mountain 1",
    "Mountain 2",
    "Mountain 3",
    "Mountain 4",
    "Mountain 5",
    "Sulfur Quarry",
    "Stone Quarry",
    "Hqm Quarry",
    "Iceberg 1",
    "Iceberg 2",
    "Iceberg 3",
    "Iceberg 4",
    "Iceberg 5",
    "Ice Lake 1",
    "Ice Lake 2",
    "Ice Lake 3",
    "Ice Lake 4",
    "Ruin A",
    "Ruin B",
    "Ruin C",
    "Ruin D",
    "Ruin E",
  ];
  schema["x-enumNames"] = schema.enum as string[];
};
