import type { SchemaPatch } from "./patches.types";

// RustMaps API incorrectly defines this enum as an integer, but it's actually a string enum
export const monumentTypesSchemaPatch: SchemaPatch = (schema) => {
  if (schema.type === "string") return;
  schema.type = "string";

  // HACK: These are unconfirmed. Based on comparing the enum names from the OpenAPI spec with the actual requests made by the Rust Maps website
  schema.enum = [
    "Airfield",
    "Apartments Complex",
    "Arctic Research Base A",
    "Bandit Town",
    "Cave Large Hard",
    "Cave Large Medium",
    "Cave Large Sewers Hard",
    "Cave Medium Easy",
    "Cave Medium Hard",
    "Cave Medium Medium",
    "Cave Small Easy",
    "Cave Small Hard",
    "Cave Small Medium",
    "Excavator",
    "Ferry Terminal",
    "Fishing Village A",
    "Fishing Village B",
    "Fishing Village C",
    "Gas Station",
    "Hqm Quarry",
    "Ice Lake 1",
    "Ice Lake 2",
    "Ice Lake 3",
    "Ice Lake 4",
    "Iceberg 1",
    "Iceberg 2",
    "Iceberg 3",
    "Iceberg 4",
    "Iceberg 5",
    "Junkyard",
    "Large Barn",
    "Large Harbor",
    "Large Oilrig",
    "Launch Site",
    "Lighthouse",
    "Military Base A",
    "Military Base B",
    "Military Base C",
    "Military Base D",
    "Military Tunnels",
    "Mountain 1",
    "Mountain 2",
    "Mountain 3",
    "Mountain 4",
    "Mountain 5",
    "Nuclear Missile Silo",
    "Outpost",
    "Powerplant",
    "Radtown",
    "Ranch",
    "Ruin A",
    "Ruin B",
    "Ruin C",
    "Ruin D",
    "Ruin E",
    "Satellite Dish",
    "Sewer Branch",
    "Small Harbor",
    "Small Oilrig",
    "Sphere Tank",
    "Stone Quarry",
    "Sulfur Quarry",
    "Supermarket",
    "Swamp A",
    "Swamp B",
    "Swamp C",
    "Trainyard",
    "Warehouse",
    "Water Treatment",
    "Water Well A",
    "Water Well B",
    "Water Well C",
    "Water Well D",
    "Water Well E",
    "Ziggurat",
  ];
  schema["x-enumNames"] = schema.enum as string[];
};
